name: Test PR

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - '__tests__/**'
      - package-lock.json
      - .nvmrc

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run coverage
      - run: npm run build
